### ISSUE TITLE
Set Example For Upload Template is Generated WIth Incorrect Values

### ISSUE THREAD

**Issue by joshunrau** [DouglasNeuroInformatics/OpenDataCapture#1002]
For the Happiness Questionnaire, the template example for `causesOfDissatisfaction` is given as `SET(a,b,c) (optional)`. In the schema, it is defined as ` z.set(z.enum(['MONEY', 'FRIENDS', 'ROMANTIC_PARTNER', 'EXISTENTIAL_CRISIS'])).optional()`

**Comment by david-roper** [comment]
Yeah this was one of the previous TODOs, will work on it now
