### ISSUE TITLE
About page fails with a 500 error

### ISSUE THREAD

**Issue by thomasbeaudry** [DouglasNeuroInformatics/OpenDataCapture#1010]
### Current Behavior

When you click on the about page on a server that isn't running the gateway service, you get three 500 error popups, and then the page gets redirected to "Something went wrong". 

### Expected Behavior

For the about page to load properly

### Browser

Chrome

### Additional Details

Taking a quick look, matybe it's linked to the gateaway health check?

### Priority

High

**Comment by joshunrau** [comment]
I cannot reproduce this locally. Is this still occurring in the latest version (1.6)?

**Comment by thomasbeaudry** [comment]
Yes is does with version 1.6

**Comment by joshunrau** [comment]
Can you please send me the error report. This should be available for v1.6.1

**Comment by joshunrau** [comment]
<img width="817" alt="Screenshot 2024-11-04 at 10 32 30 AM" src="https://github.com/user-attachments/assets/208a119c-4e05-475e-820c-828c3ae07d04">
