### ISSUE TITLE
Backend error for upload feature

### ISSUE THREAD

**Issue by david-roper** [DouglasNeuroInformatics/OpenDataCapture#1014]
### Current Behavior

When submitting csv data to the upload feature the website goes to an unexpected error page, due to it not being able to process serialized date data.

### Expected Behavior

The website should be able to process a valid date after it gets serialized by the replacer. If the date is invalid it should send an error notification to the frontend instead of crashing the site. 

### Browser

Firefox

### Steps To Reproduce

Login to an account with access to the upload feature
Enable experimental features in app settings
navigate to upload feature
select and instrument
click download template and correctly fill in data (use sample row as guidance)
drop csv file into dropzone and submit

### Additional Details

[Here](https://playground.opendatacapture.org/?files=NobwRAxg9gdgLgU3mAXGA9AKgAQIM4A2AlvALQAmReAhgEYELYAOCATgGYIRxGxVzo8UVnFJRaAKy5w82TOgA6MJUQC2TYXGwhs5BOxIIAkjDxxWAV1VItAX2ztWUVdgDk6S-DUJ0ANwCM6AACUCww5NRw1BDUTHAWrD6ePNak0ImuANwq6pra2ABe2PaOzm4eFl7WfoEFUORBAMwAdABMLQAeWUo9MAgdGiK6%2BtQWBFp6Bn0mZpbW8AAUIErY2ADWJOQobgBiAPIASgCyrgA0K9gE1DAA5hbUNwjbrkhnF1E3eNvArgAS1%2BRiLczq4AMIWJhMEg3EEAFVY1BI0NcAF1zjBViREKwYNQCNtlhjVrhKDxYNtWujidhcdZnkc9gBVADKAFEAPq-ACCADkACIAGSMPIA4uz9sdXBdbFTsNB4DYCRdVk5nDyrLQ2EqidSNuFnrNkbLqb5qKwiNc4NsFGASEwLHAbcbiVdNfjsDaDlAyjANWwbcris6ABYAoE3WEATxY2upqz1WzchuBztWpvNlutYARlCgTsDq1dCHdNp2whcUHY2FD4XD%2BZ1xNCZNMsbjqxtsMRBGwNwRtFo0JtWc7RG7vboA9u9bb7bA4Mhg9QHrnEKhU7AqeJHYsmuw1jgwfqQ%2BXsJ3jH3h-IAYbq1sgZlgZrgOhfISkV4MFbus2Wd9qk1rDTnG6YWvAWZ2g6QHUkWJZgK%2BCLNtgCyqCQDr4AAlNe1J3kSD5EnoUSjl82iBnoeAQOacQfs8fL4BRRCarIADuwZINg1zsTAah4tgTHULIT4MOQpzYEQMhygkiTwNWYbQtgeD4HgH4iQC2AHowglyRe9TYBYCnkM0bwNvgKSRAg5Dwe%2B5LYP4zokLMFjcB%2BxE-AACgw-GMAYBDdlADpqcGVAOOW2CwBAjDUHufkKQ4SJ4KxsiRZptzyYpH7NNg8FyUlskpQpeBKbAujUJGAVBewIVBf0LDcOZalQLosARfVUS%2BVWB6JIwKT4MFrC4NEwaieERC%2BEQ5D3N2%2BWFRi0DqAwiAGdgXI%2Bb1qiyJWMm1nJel1bQpXqZtgJsOxiTsSt1XSHVcANbuTFiYFGIHcyeyuaizrEOFphPG4XJMANCCkK0zQAAxGdSPBwAw9LRYw-xbSlZasKoUq4bK1j8Qk%2BBftgqqqOq-5aiRN7rD%2BbjymYYNxjBWZej6fqARuBY4-oWa4-jAFYcSeFxslEbRt9hJtgmzzk3AlPQXQxZZojFZVrzUHEok7BZrzUYsJzt4hrlNyWc22PxqTrii%2BLLqS7BusfkhKG%2BogeCYYzxNKyr2sW7AGvFNKsqmsQETNsyECsao1DbAUzTiFI3BLIGbP0yHzTJjcCzoVr8N8zGhTNEgVgLMAHZdj2faTjc%2BYrgu67nGAp67tpV5gCiyePi7b56xnf4AUnzTWwswOYbhve2Oh2QwBuYC0ggqC2uE-TNDIYC2CiQA&label=LIewrgzgpg%2BgEgQwHYBMA2BLJBzGAxEAJwFsg) is a sample for from the mouse ODC to use to test the upload feature

### Priority

High

**Comment by joshunrau** [comment]
@david-roper please provide the instrument and data

**Comment by david-roper** [comment]
heres the [form](https://playground.opendatacapture.org/?files=NobwRAxg9gdgLgU3mAXGA9AKgAQIM4A2AlvALQAmReAhgEYELYAOCATgGYIRxGxVzo8UVnFJRaAKy5w82TOgA6MJUQC2TYXGwhs5BOxIIAkjDxxWAV1VItAX2ztWUVdgDk6S-DUJ0ANwCM6AACUCww5NRw1BDUTHAWrD6ePNak0ImuANwq6pra2ABe2PaOzm4eFl7WfoEFUORBAMwAdABMLQAeWUo9MAgdGiK6%2BtQWBFp6Bn0mZpbW8AAUIErY2ADWJOQobgBiAPIASgCyrgA0K9gE1DAA5hbUNwjbrkhnF1E3eNvArgAS1%2BRiLczq4AMIWJhMEg3EEAFVY1BI0NcAF1zjBViREKwYNQCNtlhjVrhKDxYNtWujidhcdZnkc9gBVADKAFEAPq-ACCADkACIAGSMPIA4uz9sdXBdbFTsNB4DYCRdVk5nDyrLQ2EqidSNuFnrNkbLqb5qKwiNc4NsFGASEwLHAbcbiVdNfjsDaDlAyjANWwbcris6ABYAoE3WEATxY2upqz1WzchuBztWpvNlutYARlCgTsDq1dCHdNp2whcUHY2FD4XD%2BZ1xNCZNMsbjqxtsMRBGwNwRtFo0JtWc7RG7vboA9u9bb7bA4Mhg9QHrnEKhU7AqeJHYsmuw1jgwfqQ%2BXsJ3jH3h-IAYbq1sgZlgZrgOhfISkV4MFbus2Wd9qk1rDTnG6YWvAWZ2g6QHUkWJZgK%2BCLNtgCyqCQDr4AAlNe1J3kSD5EnoUSjl82iBnoeAQOacQfs8fL4BRRCarIADuwZINg1zsTAah4tgTHULIT4MOQpzYEQMhygkiTwNWYbQtgeD4HgH4iQC2AHowglyRe9TYBYCnkM0bwNvgKSRAg5Dwe%2B5LYP4zokLMFjcB%2BxE-AACgw-GMAYBDdlADpqcGVAOOW2CwBAjDUHufkKQ4SJ4KxsiRZptzyYpH7NNg8FyUlskpQpeBKbAujUJGAVBewIVBf0LDcOZalQLosARfVUS%2BVWB6JIwKT4MFrC4NEwaieERC%2BEQ5D3N2%2BWFRi0DqAwiAGdgXI%2Bb1qiyJWMm1nJel1bQpXqZtgJsOxiTsSt1XSHVcANbuTFiYFGIHcyeyuaizrEOFphPG4XJMANCCkK0zQAAxGdSPBwAw9LRYw-xbSlZasKoUq4bK1j8Qk%2BBftgqqqOq-5aiRN7rD%2BbjymYYNxjBWZej6fqARuBY4-oWa4-jAFYcSeFxslEbRt9hJtgmzzk3AlPQXQxZZojFZVrzUHEok7BZrzUYsJzt4hrlNyWc22PxqTrii%2BLLqS7BusfkhKG%2BogeCYYzxNKyr2sW7AGvFNKsqmsQETNsyECsao1DbAUzTiFI3BLIGbP0yHzTJjcCzoVr8N8zGhTNEgVgLMAHZdj2faTjc%2BYrgu67nGAp67tpV5gCiyePi7b56xnf4AUnzTWwswOYbhve2Oh2QwBuYC0ggqC2uE-TNDIYC2CiQA&label=LIewrgzgpg%2BgEgQwHYBMA2BLJBzGAxEAJwFsg)
