### ISSUE TITLE
Add time of day to retrospective session form

### ISSUE THREAD

**Issue by david-roper** [DouglasNeuroInformatics/OpenDataCapture#1049]
### Current Implementation and Limitations

Currently the session form allows for retrospective sessions and allows for the user to select the date. However with certain uses cases for ODC the time of day could be important as well.

### Associated Application Components

Client

### Proposed Solution

Allow for an optional input box or selected field to be revealed (hour and minutes) when the user selects a retrospective session in the form. Thus allowing them to put the time of day if needed.

### Estimated Difficulty

Low

### Priority

Medium

**Comment by gdevenyi** [comment]
Duplicate of #1029

**Comment by david-roper** [comment]
Closing this is due to duplication
