### ISSUE TITLE
[Discussion]: Investigate interface for shareable one-off forms

### ISSUE THREAD

**Issue by gdevenyi** [DouglasNeuroInformatics/OpenDataCapture#14]
Idea:
I want to send the happiness index form to a specific patient for them to fill out.

They should get a clickable URL that sends them straight to the form, which is pre-filled (or perhaps the state is pre-filled, but the fields are hidden), they then complete the form. The URL after this is no longer valid.

Are there libraries for this?

**Comment by joshunrau** [comment]
This should be possible to do with Next but as far as I can reason would require authentication (which I want to try and implement today). Is this workflow along what you have in mind?

- Clinician goes to page to creates URL for subject (entering names, dob)
- This generates a hash and stores it in the database
- They then copy-paste the URL which contains this hash
- The link is valid until submitted (or potentially a timeout), at which point the hash will be dropped from the database

**Comment by gdevenyi** [comment]
I would call that "authentication" per-se, but yes, this is what I'm thinking about.
