### ISSUE TITLE
[Discussion]: Look into DNP logo collection for Instrument Logo

### ISSUE THREAD

**Issue by gdevenyi** [DouglasNeuroInformatics/OpenDataCapture#275]
We have 100 premade logos.

**Comment by joshunrau** [comment]
@david-roper Please look on our Google Drive and select a logo that will look nice (I would use SVG format). Then, replace the current logo (which will be somewhere on `AvailableInstrumentsPage`, or one if it's child components with a nice DNP one. You can store the logo in `/assets` and then import it. See Vite docs for more info
