### ISSUE TITLE
[Discussion]: Upload docker builds into github docker registry

### ISSUE THREAD

**Issue by gdevenyi** [DouglasNeuroInformatics/OpenDataCapture#276]
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-docker-registry

We need a builder and a runner for client and server, then we save the binaries.

**Comment by joshunrau** [comment]
If we are switching to podman, is this necessary?

**Comment by gdevenyi** [comment]
Yes, podman is the software that runs things, the image format (and Dockerfiles) remain the same.

This only applies once we have "generic" images though.
