### ISSUE TITLE
[Enhancement]: Drop use of fd

### ISSUE THREAD

**Issue by gdevenyi** [DouglasNeuroInformatics/OpenDataCapture#511]
### Current Implementation and Limitations

The current use of `fd` in the package.json is very redundant.

This command:
https://github.com/DouglasNeuroInformatics/DouglasDataCapturePlatform/blob/b5aa381d52f634d4fb880f042b5f090486b22c2a/package.json#L17C76-L17C76
`"clean": "fd -H -I --prune \".turbo|dist|node_modules\" --exec rm -rf",`

Is equivalent to
`rm -rf .turbo dist node_modules`

### Associated Application Components

Client, Server

### Proposed Solution

Use `rm -rf .turbo dist node_modules`

### Estimated Difficulty

Low

### Priority

Low

**Comment by joshunrau** [comment]
No it is not. This finds the directories in subdirectories (e.g., `./dist` and `./api/dist).

**Comment by gdevenyi** [comment]
This command needs to be properly documented.

What is it supposed to do.
