### ISSUE TITLE
[Enhancement]: Bun Migration

### ISSUE THREAD

**Issue by joshunrau** [DouglasNeuroInformatics/OpenDataCapture#546]
### Current Implementation and Limitations

Currently, we use NPM as a package manager. The code is all written in TypeScript, which is compiled to vanilla JavaScript with the `Node16` module system (ESM). This is done using SWC. Moving our code away from the legacy `CommonJS` module system was a huge headache and can still cause compatability issues. In particular, we have to use a custom loader when running Node test coverage which causes issues with other packages that compute code coverage. 

### Associated Application Components

Client, Server

### Proposed Solution

Implement Bun.

There are two major difficulties here: the lack of support for emitting decorator metadata (some Nest functionality) and lack of support for Turbo.

Relevant Issues:
- https://github.com/oven-sh/bun/issues/1641
- https://github.com/vercel/turbo/issues/4762

Once these issues are resolved, we can migrate all packages.

### Estimated Difficulty

High

### Priority

High

**Comment by pontusab** [comment]
turbo now have beta support for bun https://x.com/turborepo/status/1702791416672387094?s=46&t=EsyqrpgYWcCvn97nnTxwww

**Comment by joshunrau** [comment]
> turbo now have beta support for bun [x.com/turborepo/status/1702791416672387094?s=46&t=EsyqrpgYWcCvn97nnTxwww](https://x.com/turborepo/status/1702791416672387094?s=46&t=EsyqrpgYWcCvn97nnTxwww)

Awesome, thanks. It is working great for me in a toy repo. I will see Monday whether that also holds for this.

**Comment by joshunrau** [comment]
https://github.com/oven-sh/bun/issues/2036
