### ISSUE TITLE
Investigate Reproschema for Implementing Forms

### ISSUE THREAD

**Issue by gdevenyi** [DouglasNeuroInformatics/OpenDataCapture#549]
### Content

https://github.com/ReproNim/reproschema

This already exists and has questionnaires in it
https://github.com/ReproNim/reproschema-library

**Comment by yibeichan** [comment]
Hi, as long as ODC is in a structured format (which looks like this), it can be converted to reproschema. I'm happy to help.

**Comment by yibeichan** [comment]
hi, thank you! i'll get back to you by next monday! and if i have any questions between now and then i'll let you know

**Comment by yibeichan** [comment]
Hii, sorry for the delay. here is the PR for the converter: https://github.com/ReproNim/reproschema-py/pull/108
this one only works for the static.
here is the mapping file: https://github.com/ReproNim/reproschema-py/blob/b8584329ac2d927c5cb06b6f302fbf7dcd7b3aeb/reproschema/odc_mappings.py

here is the test output structure:
tests/demo-output/
└── sample_clinical_assessment/
    ├── sample_clinical_assessment/           # Protocol directory
    │   └── sample_clinical_assessment_schema # Protocol schema
    └── activities/
        └── sample_clinical_assessment/
            ├── sample_clinical_assessment_schema  # Activity schema (14 items)
            └── items/
                ├── patient_name                 # Simple string field
                ├── notes                         # Textarea
                ├── age                            # Number input
                ├── pain_level                   # Number slider (range)
                ├── consent                       # Boolean checkbox
                ├── assessment_date               # Date field
                ├── gender                         # Single-select (radio)
                ├── symptoms                       # Multi-select (listbox)
                ├── medication_frequency          # Single-select (select)
                ├── satisfaction_likert_overall  # Likert item 1/3
                ├── satisfaction_likert_wait_time # Likert item 2/3
                ├── satisfaction_likert_staff_helpfulness # Likert item 3/3
                ├── medical_history_condition      # Record array field 1/3
                ├── medical_history_year_diagnosed # Record array field 2/3
                └── medical_history_treated            # Record array field 3/3

let me know what you think

**Comment by gdevenyi** [comment]
Triaging upstream: there was prior investigation and a linked reproschema-py converter PR. Is this integration still being pursued, or should this issue be closed as investigated?

**Comment by gdevenyi** [comment]
Following up here, is there anything we can support to get this merged?

**Comment by yibeichan** [comment]
hey @joshunrau did you get a chance to test it? let me know what else i/repronim can do

**Comment by joshunrau** [comment]
@yibeichan oops, very sorry this fell through the cracks. I will have a look right now.

**Comment by joshunrau** [comment]
@yibeichan thanks for your work on this. Again, very sorry for the delay on this. I had a look over everything and I am going to leave more review comments this weekend after a fresh look (very long day).

In general, I think it makes a lot of sense. The main issue I see here is this doesn't work with multilingual instruments. I would suggest to add another test case with a multilingual example (I can generate one tomorrow for you).

I also assume we need to find some way to convert ODC instruments to JSON? I can try and implement this if you want. Is there anything else you need on my end here?
