### ISSUE TITLE
[Feature]: Set DNS for `gateway.opendatacapture.org` for demo

### ISSUE THREAD

**Issue by joshunrau** [DouglasNeuroInformatics/OpenDataCapture#559]
### Description

I am working on the gateway. I think it would make sense to put the demo gateway on a subdomain since it will best reflect the actual deployment (I could do reverse proxy, but doesn't really make sense for real deployment).

### Estimated Difficulty

Low

### Priority

High

**Comment by gdevenyi** [comment]
demogateway.douglasneuroinformatics.ca now points at cloud1
