### ISSUE TITLE
Rename "Add Visit" menu header

### ISSUE THREAD

**Issue by thomasbeaudry** [DouglasNeuroInformatics/OpenDataCapture#566]
### Content

The "Add Visit" menu header is misleading.  In reality, you are adding a subject, so it should be "Add Subject".  Currently, on the "Add Visit" page, you aren't creating a visit label, entering a date, or selecting a subject.  In reality, you are only creating a subject by specifying a name, birthday and sex.  Additionally, if you try and enter the same data a second time (in case you thought you were going to add another visit for the same subject), you get an error message telling you that the subject has already been registered.  If the goal of this is to create visits, then you need to add the visit label and visit date field to the page.

**Comment by gdevenyi** [comment]
> you get an error message telling you that the subject has already been registered

So this is the actual bug @joshunrau 

The reason this is add visit, is because "A client attends the clinic" is a piece of data regardless of if any other forms are filled out. This interface is designed for this purpose.

If you can propose a better interface to handle this I'll hear it, but this is not supposed to be "Add Subject"

**Comment by thomasbeaudry** [comment]
Then I propose you add a date to the visit at the very least.  It makes the visit unique and removes the bug

**Comment by gdevenyi** [comment]
Adding a "date assessed" should be a subset of #460, and I agree this form needs it.

The bug is still the backend doesn't know the difference between create subject and add visit, this may need an API change.

**Comment by joshunrau** [comment]
We could change the API. Basically, what I did was rename the previous add subject page to add visit. The form is the same to create a new subject in the database. If we want to change the API in this way, then I think an in-person meeting next week would be helpful to discuss how this fits in with our current conception of the platform.

**Comment by joshunrau** [comment]
This is done in the latest version
