### ISSUE TITLE
Base Instrument Metadata

### ISSUE THREAD

**Issue by joshunrau** [DouglasNeuroInformatics/OpenDataCapture#580]
### Content

What should it be?

**Comment by joshunrau** [comment]
Add schema version.

**Comment by gdevenyi** [comment]
Creation date

**Comment by gdevenyi** [comment]
Origin?

**Comment by joshunrau** [comment]
What do you mean origin?

**Comment by joshunrau** [comment]
If this is just for internal notes, we can just have a dictionary `Record<string, string>`where we can put anything?

**Comment by gdevenyi** [comment]
We could do that, what I'm more thinking about is minimum "required" metadata, for clear identification of things.
