### ISSUE TITLE
[Feature]: Implement Instrument Series

### ISSUE THREAD

**Issue by joshunrau** [DouglasNeuroInformatics/OpenDataCapture#593]
### Description

This needs to be done asap

### Estimated Difficulty

Medium

### Priority

High

**Comment by gdevenyi** [comment]
Series instruments need some kind of "resumability", maybe only on the external gateway.

Reason for this is something like:
- user is assigned series instrument for external gateway
- user partially completes (i.e. does say 4/10 instruments)
- user closes window to return later
- user accesses the same URL again

**Comment by gdevenyi** [comment]
Can we achieve general resumability on the gateway via LocalStorage?

How do we do it for the gateway but not the base install?

**Comment by joshunrau** [comment]
Yes, we could. I don't think it would be that difficult to implement, assuming it is okay to store the saved results as plain text?
