### ISSUE TITLE
Dark Mode in Interactive Instrument

### ISSUE THREAD

**Issue by joshunrau** [DouglasNeuroInformatics/OpenDataCapture#622]
### Content

Since interactive instruments involve arbitrary CSS, they may not be adapted to dark mode, and be unusable in dark mode.  

Options
- Force light mode in entire app when in interactive instrument
- Add light canvas for interactive instruments
- ???

**Comment by gdevenyi** [comment]
> unusable in dark mode.

Is this because both CSS stylesheets are included?

**Comment by joshunrau** [comment]
> > unusable in dark mode.
> 
> Is this because both CSS stylesheets are included?

No, it is because we have custom styles for dark mode (for details on how it works, see https://tailwindcss.com/docs/dark-mode). However, since the instrument is rendered in an iframe, it is not affected by our CSS (by design). However, in the (almost certain) case where the instrument does not adjust styling depending on the `prefers-color-scheme` and `[data-mode="dark"]`, it will stay the same while everything else changes.

**Comment by gdevenyi** [comment]
Ok, so this is OK and I think correct, especially in the cases where an instrument might be from elsewhere, and "validated" under whatever style sheet was used.

I was thinking about if we should support and/or enforce the instrument being in a popup instead to avoid making this clash badly (also moves us toward the requested "two window" approach)
