### ISSUE TITLE
Encryption Implementation

### ISSUE THREAD

**Issue by joshunrau** [DouglasNeuroInformatics/OpenDataCapture#623]
### Content

Standard library for encryption:
- [DiffieHellman](https://nodejs.org/api/crypto.html#class-diffiehellman)
- crypto.privateDecrypt(privateKey, buffer)
- Look at NIST standards

When creating assignment, create new record in core database with public and private key pair. Transmit public key with assignment to remove. Encrypt with public key on gateway. When main collects data, collect and decrypt.

**Comment by gdevenyi** [comment]
https://csrc.nist.gov/pubs/sp/800/133/r2/final

**Comment by gdevenyi** [comment]
Implementation example using RSA
https://gist.github.com/sohamkamani/b14a9053551dbe59c39f83e25c829ea7

**Comment by gdevenyi** [comment]
I think in the end, I'd prefer to use https://nodejs.org/api/webcrypto.html with a 2048-bit RSA-OAEP keypair
