### ISSUE TITLE
How to Handle Runtime Imports

### ISSUE THREAD

**Issue by joshunrau** [DouglasNeuroInformatics/OpenDataCapture#638]
### Content

Currently, the runtime is required for the API, Gateway, and Web. Each of these services has a separate implementation to serve the static runtime assets. Would it be better to move this into it's own service?

**Comment by joshunrau** [comment]
Can be esbuild plugin?

**Comment by gdevenyi** [comment]
> Would it be better to move this into it's own service?

I'm not a fan of another service, because I can imagine heavily-firewalled instances where sometimes the service won't/can't be available across a boundary.
