### ISSUE TITLE
[Bug]: Strong password regex breaks with special characters

### ISSUE THREAD

**Issue by joshunrau** [DouglasNeuroInformatics/OpenDataCapture#644]
### Current Behavior

ISee attached

<img width="596" alt="Screenshot 2024-02-08 at 1 55 27 PM" src="https://github.com/DouglasNeuroInformatics/OpenDataCapture/assets/78170036/58e60ed5-182d-4d73-8c3b-13db60b0feb1">

### Expected Behavior

The regex should work properly. Look into other issue for an alternative password strength implementation.

### Priority

High

**Comment by gdevenyi** [comment]
Is this custom? There should be a good npm package for this.

https://github.com/zxcvbn-ts/zxcvbn

**Comment by joshunrau** [comment]
> Is this custom? There should be a good npm package for this.
> 
> https://github.com/zxcvbn-ts/zxcvbn

Perfect, this is exactly what we need. I remember looking at the old coffeescript version at some point, but it was abandoned.
