### ISSUE TITLE
[Enhacement] Provide easy interface in data view to query active visit subject

### ISSUE THREAD

**Issue by gdevenyi** [DouglasNeuroInformatics/OpenDataCapture#656]
If I'm already in an active visit, provide an interface to easily lookup that subject.

**Comment by joshunrau** [comment]
We already have this. If you click on the search bar the current active subject will automatically be filled out

**Comment by joshunrau** [comment]
Do you mean something else?

**Comment by gdevenyi** [comment]
This is ok, but not particularly discoverable. I suspect the most common use case will be to lookup the current subject, so I think it should be right there.
