### ISSUE TITLE
Investigate Potentially Extraneous Testing Libraries

### ISSUE THREAD

**Issue by joshunrau** [DouglasNeuroInformatics/OpenDataCapture#684]
David, we have the following libraries in `apps/web/package.json`:

```json
{
  "devDependencies": {
    "@testing-library/dom": "^9.3.4",
    "@testing-library/jest-dom": "^6.2.0",
    "@testing-library/react": "^14.1.2",
    "@testing-library/user-event": "^14.5.2",
    "jsdom": "^23.2.0",
  },
}
```
Please check if these are being used for something. If not, remove them and make sure the tests still work.

**Comment by david-roper** [comment]
Just tested it now these packages are not needed to run the E2E test suite.

**Comment by joshunrau** [comment]
Okay great please make a PR to remove. We will add later if needed for something else.
