### ISSUE TITLE
Add Image Object form field

### ISSUE THREAD

**Issue by thomasbeaudry** [DouglasNeuroInformatics/OpenDataCapture#756]
### Description

It should be possible to add an image object to an instrument.  You can set the scale and dimensions of it when you define the form field.  This should be done through the implementation of an image object form field.

### Estimated Difficulty

Medium

### Priority

Low

**Comment by joshunrau** [comment]
This is not realistic to implement at this time and in the manner proposed. If this is required for some form, please discuss with me and we can implement as an interactive instrument. Thanks
