### ISSUE TITLE
Open Data Capture doesn't load forms in Netscape Navigator

### ISSUE THREAD

**Issue by thomasbeaudry** [DouglasNeuroInformatics/OpenDataCapture#758]
### Current Behavior

I connect to my AOL provider and go to the platform. I wait forever and no form loads, and no login.  I think you should build your platform with Malboge instead!

### Expected Behavior

Much awesomeness

### Steps To Reproduce

Buy a high performance desktop from charlie657 on eBay and use it to web browse. Charlie had the best machines and no one else's will work. This is what he taught me through his $3900 e-course.

### Priority

High

**Comment by gdevenyi** [comment]
We need to enable JS 1.0 build spec to get the JS to run clearly.
