### ISSUE TITLE
formplayground refreshes the editor component when you resize your web browser.

### ISSUE THREAD

**Issue by thomasbeaudry** [DouglasNeuroInformatics/OpenDataCapture#770]
### Current Behavior

If you are editing an instrument in the playground, when you resize your web browser, it doesn't save your edits in the editor component, and refreshes the original instrument you had loaded, and all your edits are lost.

### Expected Behavior

for the edits to be saved when you resize the browser

### Browser

Chrome

### Steps To Reproduce

1. load an instrument
2. type some characters into the editor component
3. resize your browser
4. cry when your edits are lost!

### Priority

Medium

**Comment by joshunrau** [comment]
saving now exists which should mitigate this
