### ISSUE TITLE
Playground right-side margin should be larger

### ISSUE THREAD

**Issue by gdevenyi** [DouglasNeuroInformatics/OpenDataCapture#810]
Overlapped by the scrollbar, not sure if this also happens in the real deployment
![image](https://github.com/DouglasNeuroInformatics/OpenDataCapture/assets/3001850/49da9220-2379-462c-b21f-93cc6fe36567)

**Comment by joshunrau** [comment]
Duplicate of #791. This is not trivial to fix and will do it after vacation.

**Comment by gdevenyi** [comment]
Gabe can't forget what he's done in the past.
