### ISSUE TITLE
Consider How to Handle React v19

### ISSUE THREAD

**Issue by joshunrau** [DouglasNeuroInformatics/OpenDataCapture#866]
In the React documentation, the following is written regarding the JSX transform:

> The functions inside react/jsx-runtime and react/jsx-dev-runtime must only be used by the compiler transform. If you need to manually create elements in your code, you should keep using React.createElement. It will continue to work and is not going away.

Despite this, React is removing support for the classic`React.createElement` transform in v19. It seems like it will not be fully removed, but continuing to use it will prevent the performance optimizations associated with the new compiler. This is a problem because our runtime implements JSX via the classic transform (it is much more straightforward). Most likely, we can update the app to React v19 while maintaining React v18 in the runtime (no support for v19 until required).

**Comment by gdevenyi** [comment]
Is there an issue pointing out this conflict in docs vs intent?
