### ISSUE TITLE
Please consider showing example of integrating with InfluxDB 

### ISSUE THREAD

**Issue by suyashcjoshi** [DouglasNeuroInformatics/OpenDataCapture#884]
### Current Implementation and Limitations

I would like to use OpenDataCapture and store data in InfluxDB. It would be nice to see an example of how to do the same.

### Associated Application Components

Client

### Proposed Solution

Blog, Article, Sample Code etc

### Estimated Difficulty

Medium

### Priority

Medium

**Comment by suyashcjoshi** [comment]
Not sure which label would be appropriate, please feel free to edit.

**Comment by joshunrau** [comment]
Unfortunately, this is not really something that can be done via configuration. We use [Prisma](https://www.prisma.io/) to connect to the MongoDB database, and as far as I can tell, [Prisma does not support InfluxDB](https://www.prisma.io/docs/orm/overview/databases). If this is something you wanted to do, you would have to write code for the API by replacing the Prisma module with something connecting to your InfluxDB. At this time, this is not something we are able to devote time to, but if you want to do it I would be happy to tell you where to start (create another issue or contact me by email).

**Comment by suyashcjoshi** [comment]
Ah, that's unfortunate but since you told me, I've opened an issue with Prisma and hopefully they will integrate it soon: https://github.com/prisma/prisma/issues/24893
