### ISSUE TITLE
Add a full screen feature for instruments

### ISSUE THREAD

**Issue by carona898** [DouglasNeuroInformatics/OpenDataCapture#945]
### Description

I would like to propose the addition of a full screen mode for instruments in the application.

Providing a full screen option for instruments would enhance the user experience by allowing users to focus entirely on the instrument's interface without distractions from other elements on the screen. This is especially important in cognitive experiments or assessments, where attention to detail and immersion can significantly impact performance and data quality.

### Estimated Difficulty

Low

### Priority

Low

**Comment by joshunrau** [comment]
This is done and will be included in the next version (likely v1.7.0)
