### ISSUE TITLE
admin password can't have a !

### ISSUE THREAD

**Issue by thomasbeaudry** [DouglasNeuroInformatics/OpenDataCapture#956]
### Current Behavior

On the setup page of odc, I couldn't have a password with an exclamation mark ! 

### Expected Behavior

Let me add awesome !!!!!'s to my password :)

### Browser

Chrome

### Priority

High

**Comment by joshunrau** [comment]
no issue

**Comment by thomasbeaudry** [comment]
Yes it's an issue.  See the screenshot
![passwordwith!](https://github.com/user-attachments/assets/6d04281a-e8f4-42b7-8bd1-09254ad2d348)

If i removed the ! from the password, it accepted it.

**Comment by joshunrau** [comment]
I am pretty sure you are running an old version of the platform? Can you check?

**Comment by joshunrau** [comment]
There should now be a strength bar

**Comment by thomasbeaudry** [comment]
okay switching the release_channel=latest worked.  This is no longer an issue
